### PR TITLE
Include Options for child process to increase MaxBuffer limitation

### PR DESCRIPTION
**Pull request by Tin-Nguyen**
```
merge(srcs, destFile, {maxBuffer: 1024 * 1000}, function(err) {
    // do any thing
});
```

@karuppiah7890 , please help to review and merge the PR to enhance the lib. Thanks

### CODE REVIEW

**Comment by Tin-Nguyen** [comment]
@karuppiah7890 , could you review and give me your feedback?

**Comment by karuppiah7890** [comment]
@Tin-Nguyen I am sorry. I did see all your comments and PR. I am just too busy to check everything and merge the PR. I will get back to you!

**Comment by karuppiah7890** [comment]
Hey, what if the user uses more PDFs and if there's more output - `stdout` or `stderr`, which is more than 500kB ? Then there will be error again right ? And I don't want to expose this option to the user. The library is very neat and very very abstract. And this `maxBuffer` option is a very low level detail. If I expose this, I must explain this to the user. And he/she may not even know how much output the command will produce, since they won't know much about PDFBox. So, I gotta find a better way. I will think about it. Or we will refine this code in a better manner. First I gotta check about how to reduce the standard output produced by the PDFBox command. You are welcome to explore too :smile:

**Comment by Tin-Nguyen** [comment]
Sounds good, but I think providing `options` in the lib will help the user be more flexible for their case, it's better for a library.

We can define some owned options. Instead of `maxBuffer`, we can name it as a different name and explain to the user what it is.

**Comment by karuppiah7890** [comment]
But that consequently means we have to explain about the standard output of PDFBox command. I will get back to this issue soon. Busy with my college project for now

**Pull request merged**
