### PR TITLE
Upgrade Pdfbox from 2.0.1->2.0.11

### PR DESCRIPTION
**Pull request by alexhughesnab**
There are a bunch of bug fixes included in this with no breaking changes.

### CODE REVIEW

**Comment by alexhughesnab** [comment]
@karuppiah7890 :)

**Comment by karuppiah7890** [comment]
I will check this out soon :) thanks for the PR!

**Comment by karuppiah7890** [comment]
Thanks a lot @alexhughesnab for this 😄 🎉

**Comment by karuppiah7890** [comment]
I will release a new version soon 😄

**Comment by alexhughesnab** [comment]
@karuppiah7890 Thanks! If you don't have the time to maintain this project anymore I am willing to help out. I use this in production btw. @g0ddish is my primary github account.

**Comment by karuppiah7890** [comment]
Actually yes, I don't have time to maintain this project. I can give you
access to the GitHub project and to the npm package soon. And it's awesome
that you are using it in production. Let me know how it's working out
because there are still lots of open issues in this project that I haven't
solved. May be you can check them out and it might help your system :)

**Comment by alexhughesnab** [comment]
Yes we are aware of some of the issue, I'm going to do my best to get them all wrapped up. It's been working great so far with some minor hiccups such as outdated pdfbox 🙂 . Talk again soon!

**Pull request merged**
